add auth and user
Ivan-Bir/homework-1-spring-2023 pull request #4
Opened 2023-03-04 14:45 UTC by Mike5535

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +### Авторизация и регистрация
По структуре это заголовок 2-го уровня. Так более заметы ф-ые блоки

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +1. Есть ограничение на количество вводимых символов
Конкретнее сколько символов

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +2. Надписи соответсвуют нужным полям
Если это заголовки, то мне кажется это и так очевидно. Их ты имел в виду?
Другое дело ошибки

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +1. Если ввести почту без @ появляется сообщение: Такого адреса не существует
@ -> "@"
Такого адреса не существует -> "Такого адреса не существует"
Такие вещи думаю стоит оборачивать в кавычки

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +1. Если ввести почту без @ появляется сообщение: Такого адреса не существует
и далее в документе

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +3. При вводе пароля без цифры появляется сообщение: В пароле должна быть хотя бы одна цифра, маленькая и большая буква
Не хватает кейса на одну маленькую и большую букву

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +
Не описаны кейсы, когда ошибки пропадают

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +4. Если зажать левую кнопку мыши в пределах окна, и отпустить за его пределами, оно не закроется_**`BUG`**_
Может слегка переформулируем?
Речь же идёт о том, что окно должно закрыться при клике вне области, а не об отпускании мыши.
Давай баг описывать так, чтобы было видно как оно сейчас работает. Как раз обратная формулировка "ожидаемого поведения" сюда подойдёт

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +4. Текст ошибки имеет достаточный размер на всех экранах_**`BUG`**_
Не понятно, что значит "достаточный". Баг стоит описать словами

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +1. Во время отправки фото появляется модальное окно с просьбой подождать окончания загрузки
модальное окно -> плашка/тостер/сообщение

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +2. Дата регистрации указана в формате день(число) месяц(слово) год(число)
дд.мм.гггг

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +3. Если оценок или рецензий нет, то в поле оценки надпись: не оценок, а в графе рецензии: нет рецензий
опечатка: "нет оценок"

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +4. После того, как оценили фильм, в профиле увеличилось количество оценок, также после публикации рецензии, их количество в профиле увеличилось
увеличилось на сколько? 5, 10?
А уменьшится может?

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +1. Если отправить фото слишком большого размера появляется модальное окно с сообщением об ошибке
модальное окно -> плашка/тостер/сообщение красного цвета

2023-03-04 16:37 UTC, Ivan-Bir commented on BugOverload.md
> +_Время на тест: 8 мин._
Правда 8?

2023-03-04 19:02 UTC, Mike5535 commented on BugOverload.md
> +2. Надписи соответсвуют нужным полям
ну проверить то надо, например, вводишь почту, а отправляется пароль

2023-03-06 11:15 UTC, lonkidely commented on BugOverload.md
> +2. Надписи соответсвуют нужным полям
2 пункт опечатка, "соответсТвуют"

2023-03-06 11:32 UTC, lonkidely requested changes

2023-03-06 11:32 UTC, lonkidely commented on BugOverload.md
>  2. Надписи соответсвуют нужным полям
Всё ещё пропущена "Т" во 2 пункте, "соответсТвуют" :)

2023-03-06 11:32 UTC, lonkidely commented on BugOverload.md
> +4. Текст ошибки имеет достаточный для чтения размер на всех экранах_**`BUG`**_
Пункт 4. А в чем баг? Где суть ошибки?

2023-03-06 11:32 UTC, lonkidely commented on BugOverload.md
> +5. После публикации рецензии_**`BUG`**_, общее количество рецензий в профиле увеличилось на 1_**`BUG`**_
Пункт 5. Опять же, в чем баги то?

2023-03-06 11:33 UTC, lonkidely requested changes

2023-03-06 11:33 UTC, lonkidely commented on BugOverload.md
> +2. Фото профиля загружается на сервер, обновлясь на клиенте_**`BUG`**_
Пункт 2. В чем баг?

2023-03-06 20:49 UTC, Ivan-Bir commented on BugOverload.md
> +2. Надписи соответсвуют нужным полям
Михаил, тогда так и пиши, что введенные данные соответствуют полям в отправляемом json

2023-03-06 20:49 UTC, Ivan-Bir commented on BugOverload.md
> +6. После публикации рецензии_**`BUG`**_, общее количество рецензий в профиле увеличилось на 1_**`BUG`**_
Не ясно в чём состоит баг. Не публикуется рецензия? Счетчик увеличивается на 42?
Баг не всегда противоположное поведение ожидаемому, поэтому хочется видеть что работает не так

2023-03-06 20:49 UTC, Ivan-Bir commented on BugOverload.md
> +4. Если зажать левую кнопку мыши в пределах окна, и отпустить за его пределами, оно закроется_**`BUG`**_
Описан баг, а не ожидаемое поведение. Можем перенести как баг во второй пункт?

2023-03-07 04:41 UTC, lonkidely commented on BugOverload.md
> +2. Надписи соответсвтуют полям отправляемого json
2 пункт, не там "Т" добавил))
соответствуют

2023-03-07 04:41 UTC, lonkidely commented on BugOverload.md
> +2. Фото профиля загружается на сервер, обновлясь на клиенте_**`BUG`**_: не получилось загрузить фото
Не очень содержательный багрепорт, может ты картинку слишком большую пытался загрузить? На бэкенде ограничение стоит же

2023-03-07 07:29 UTC, Mike5535 commented on BugOverload.md
> +2. Фото профиля загружается на сервер, обновлясь на клиенте_**`BUG`**_: не получилось загрузить фото
Так вообще никакое не грузит, ни большое ни маленькое, попробуй сам

2023-03-07 14:49 UTC, lonkidely approved these changes
аппрув

2023-03-07 16:38 UTC, Ivan-Bir commented
Аппрув

2023-03-07 17:22 UTC, merged